language: node_js
node_js:
- iojs
deploy:
  provider: heroku
  api_key:
    secure: t7vzcIlJX2+murFcYcBfZf4DUOZr0uESWVshHWZYK0ZJ5r4M9YEqapcVKHkg8Hxnrxwkmf2TadFr1eF0t0WgmFtBzLRM8tlNBWw6fKL0bApmmmdQ35MNnT4joI3VZZ0SXYkiODvEwwa/+LythF/mWNclfJb0kBS6HaC5JVGKUJdMRkn640O89usnK97IxfYr0qkGohSYzK/VniMAOtYiseTLkpTsgJ1cseIlSf23D286VyH1WRSZZfQ4+DxrTJZBKYErr+rZev7Mlctbur0QZTUAgqjWal0FKYoyZ1y81CdCh3H7oG58F2Unc9Ha5RGwro9LqhDZXYeWSctoSh3Yz2yX4Y9eagbTzsr9RNtMZRxtnW4FuZj3r6vTFkRJ5pUYrVxlWRn5jzmCsIuaJCLe8V8hTs7bN5BWkFlYMZBmHhAzH6J9WFY5aww3G+p57PokmWJj7fyh6U9KufF3mk/3AJZ4RG6sem2DY+ev9FU0kPGPbudSIOqxBePuUXLyTum/yF1bPS3zDgTwEOsMKkbsDEwIbCXHBxAIw1NBUh7jaMutO6rGR0iVGfJA0t/6f+JwINz87LcZK5QId8UymPoFslXISskFW6eOJ134D8rvEuqC1QidBbIdUrAchm3El5OZOmHaASHr1CAUsRkjaAjSDoUVtVNXg8OyC4Bruye5iDA=
  app:
    master: camhsready
    develop: camhsready-staging
